name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Собираем образ из корневой директории репозитория
    - name: Build Application Image
      run: |
        docker build . \
          --file Dockerfile \
          --tag ksusha/library-app:${{ github.sha }}

    # Проверяем, что образ действительно создался
    - name: Verify Image
      run: docker images | grep library-app
